#!/bin/bash
# Update the list of available packages and their versions
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Enable HAProxy to be started by the init script
sudo systemctl enable haproxy

# Configure HAProxy
echo "
frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server 376071-web-01 54.236.30.154:80 check
   server 376071-web-02 54.152.91.4:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply the configuration changes
sudo systemctl restart haproxy

